### ISSUE TITLE
Is there correlation coefficience in output?

### ISSUE THREAD

**Issue by lhquixotic** [xuefeicao/tdcca#1]
I am not clear which file the outputs are in. Are they in 'W.pkl'?
I wonder whether the correlation coefficience between 2 time series is calculate in the code?
If yes, where can I find it?
Thx~

**Comment by xuefeicao** [comment]
Yes, it is saved in W.pkl. Just load the pickle file and you should be able to find all estimated parameters in there. let me know if you have other questions.
